"""Monthly classroom schedule image generation from Notion."""

from __future__ import annotations

import logging

from .monthly_schedule_fonts import (
    ASCII_RUN_RE,
    COURIER_ASCENT_OVERRIDE,
    COURIER_BOLD_URL,
    COURIER_DESCENT_OVERRIDE,
    COURIER_LINE_GAP_OVERRIDE,
    COURIER_REGULAR_URL,
    COURIER_SIZE_ADJUST,
    ZEN_BOLD_URL,
    ZEN_REGULAR_URL,
    _download_font,
    _draw_centered_mixed_text,
    _draw_mixed_text,
    _fit_font_set_to_width,
    _font_height,
    _is_ascii_char,
    _is_valid_font_path,
    _load_font_set,
    _mixed_font_height,
    _mixed_text_bbox,
    _mixed_text_width,
    _resolve_required_font_paths,
    _resolve_single_font,
    _scale_font_set,
    _split_text_runs,
    _text_width,
    _truncate_mixed_text,
)
from .monthly_schedule_models import (
    JST,
    DayCard,
    ScheduleEntry,
    ScheduleFontPaths,
    ScheduleFontSet,
    ScheduleJsonSourceConfig,
    ScheduleRenderConfig,
    ScheduleSourceConfig,
)
from .monthly_schedule_render import (
    PALETTE,
    WEEKDAY_LABELS,
    default_schedule_filename,
    image_to_bytes,
    save_image,
    _apply_clear_warm_background_style,
    _create_gradient_background,
    _draw_day_events,
    _pick_smaller_font_set,
)
from .monthly_schedule_sources import (
    MonthlyScheduleNotionClient,
    extract_month_entries_from_json,
    _build_entry_from_any_date,
    _build_entry_from_dict,
    _extract_rich_text,
    _extract_text,
    _parse_date_ymd,
    _parse_json_datetime,
    _parse_notion_datetime,
    _pick_text,
    _to_text,
)
from .monthly_schedule_text import (
    CLASSROOM_CARD_STYLES,
    NIGHT_BADGE_STYLE,
    VENUE_BADGE_STYLES,
    build_monthly_caption,
    _build_day_cards,
    _build_fixed_time_rows,
    _expand_time_values,
    _extract_start_hour_from_time_text,
    _format_clock,
    _format_time_range,
    _get_classroom_card_style,
    _get_venue_badge_style,
    _is_night_entry,
    _is_night_time_text,
    _merge_time_text,
    _normalize_hashtags,
    _normalize_slot,
    _resolve_night_time_line_indexes,
    _short_classroom_name,
    _time_text_to_sort_key,
)
from .monthly_schedule_utils import (
    _calendar_visible_date_range,
    _entry_sort_key,
    _safe_positive_int,
    resolve_target_year_month,
)

logger = logging.getLogger(__name__)

# Keep module-level indirection so tests that monkeypatch
# monthly_schedule._resolve_required_font_paths/_load_font_set continue to work.
from . import monthly_schedule_render as _render_module


def render_monthly_schedule_image(
    year: int,
    month: int,
    entries: list[ScheduleEntry],
    config: ScheduleRenderConfig,
):
    _render_module._resolve_required_font_paths = _resolve_required_font_paths
    _render_module._load_font_set = _load_font_set
    return _render_module.render_monthly_schedule_image(year, month, entries, config)


__all__ = [
    "ASCII_RUN_RE",
    "CLASSROOM_CARD_STYLES",
    "COURIER_ASCENT_OVERRIDE",
    "COURIER_BOLD_URL",
    "COURIER_DESCENT_OVERRIDE",
    "COURIER_LINE_GAP_OVERRIDE",
    "COURIER_REGULAR_URL",
    "COURIER_SIZE_ADJUST",
    "DayCard",
    "JST",
    "MonthlyScheduleNotionClient",
    "NIGHT_BADGE_STYLE",
    "PALETTE",
    "ScheduleEntry",
    "ScheduleFontPaths",
    "ScheduleFontSet",
    "ScheduleJsonSourceConfig",
    "ScheduleRenderConfig",
    "ScheduleSourceConfig",
    "VENUE_BADGE_STYLES",
    "WEEKDAY_LABELS",
    "ZEN_BOLD_URL",
    "ZEN_REGULAR_URL",
    "build_monthly_caption",
    "default_schedule_filename",
    "extract_month_entries_from_json",
    "image_to_bytes",
    "render_monthly_schedule_image",
    "resolve_target_year_month",
    "save_image",
    "_apply_clear_warm_background_style",
    "_build_day_cards",
    "_build_entry_from_any_date",
    "_build_entry_from_dict",
    "_build_fixed_time_rows",
    "_calendar_visible_date_range",
    "_create_gradient_background",
    "_download_font",
    "_draw_centered_mixed_text",
    "_draw_day_events",
    "_draw_mixed_text",
    "_entry_sort_key",
    "_expand_time_values",
    "_extract_rich_text",
    "_extract_start_hour_from_time_text",
    "_extract_text",
    "_fit_font_set_to_width",
    "_font_height",
    "_format_clock",
    "_format_time_range",
    "_get_classroom_card_style",
    "_get_venue_badge_style",
    "_is_ascii_char",
    "_is_night_entry",
    "_is_night_time_text",
    "_is_valid_font_path",
    "_load_font_set",
    "_merge_time_text",
    "_mixed_font_height",
    "_mixed_text_bbox",
    "_mixed_text_width",
    "_normalize_hashtags",
    "_normalize_slot",
    "_parse_date_ymd",
    "_parse_json_datetime",
    "_parse_notion_datetime",
    "_pick_smaller_font_set",
    "_pick_text",
    "_resolve_night_time_line_indexes",
    "_resolve_required_font_paths",
    "_resolve_single_font",
    "_safe_positive_int",
    "_scale_font_set",
    "_short_classroom_name",
    "_split_text_runs",
    "_text_width",
    "_time_text_to_sort_key",
    "_to_text",
    "_truncate_mixed_text",
]
