name: Test Schedule

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Log Time
        run: |
          echo "Schedule triggered successfully"
          date
